### PR TITLE
Add OpenCV render window mode

### LINKED ISSUE #1: pyglet.gl.lib.GLException: b'invalid enumerant'
Hi Xingdong, thanks for this great wrapper! This is exactly what I was looking for :)

I have discovered an OpenGL context bug in `pyglet` that will cause [`gym.envs.classic_control.rendering.SimpleImageViewer`](https://github.com/zuoxingdong/dm2gym/blob/f010373356f657d2d15787c7f061263cdb901e16/dm2gym/dm_control_env.py#L67) to crash every time under certain OpenGL driver configurations if `dm_control` is currently being used to render scenes (e.g. I'm using Windows 10 64bit, Python 3.6.6, Pyglet 1.4.0b1 with a GeForce MX150 and driver version 430.39). This makes the `dm2gym` wrapper unusable if doing human-mode rendering. This bug has been reported to the `pyglet` team [here](https://bitbucket.org/pyglet/pyglet/issues/97/pygletgllibglexception-invalid-operation) and [here](https://bitbucket.org/pyglet/pyglet/issues/159/pygletgllibglexception-binvalid-enumerant) but there isn't any known fix yet.

I'm creating an issue here for the bug because I've developed a patch for `dm2gym` that adds an alternate rendering mode based on OpenCV that is performant and avoids this crashing bug. I'll send the PR shortly - hopefully we can work to get this merged into the repo :)

Thanks!

### PR DESCRIPTION
**Pull request by aaronsnoswell**
This PR adds a workaround to fix #1 by creating an alternate human render window option, based on the python-opencv library.

I've tried to make minimal changes, but I did add some spacing and comments in the render function and constructor to clarify what the new code does.

Looking forward to your comments and/or merging this PR :)

### CODE REVIEW

**Comment by zuoxingdong** [comment]
Hi @aaronsnoswell , thanks a lot for pointing out this problem and for this PR ! It looks great, I just have two tiny discussions:

- I think it's better to put render option to `render()` function, say in kwargs, instead of `__init__`, in this case, probably it's not necessary to have docstring for constructor. (in `gym.Env` class they already have docstring for the explanation of APIs)

- Perhaps it can be a good idea to create a OpenCV-based class, something like `OpenCVImageViewer` and call this class within the option in the same style of `SimpleImageViewer`. This would make the code clean and consistent. 

What do you think ?

**Comment by aaronsnoswell** [comment]
Hi @zuoxingdong, your suggestions sound good - I'll make both changes and re-submit in the next day or so for re-reivew :)

**Comment by aaronsnoswell** [comment]
Ok, please see the updated changes - I've broken out a separate `OpenCVImageViewer` class now, and the option argument is in the `render()` function. I couldn't put it in the `kwargs` because that gets passed to the physics render() method :)

**Comment by zuoxingdong** [comment]
Hi @aaronsnoswell , that looks awesome ! Just one last point about PEP8 coding style, could you remove the additional blank lines particularly in render, this would fit PEP8 and with consistent coding style ?

- dm_control_env
  - [1](https://github.com/zuoxingdong/dm2gym/pull/2/files#diff-a2334ef9c72b0a95fe36fdf91f254b60R34), [2](https://github.com/zuoxingdong/dm2gym/pull/2/files#diff-a2334ef9c72b0a95fe36fdf91f254b60R62), [3](https://github.com/zuoxingdong/dm2gym/pull/2/files#diff-a2334ef9c72b0a95fe36fdf91f254b60R66), [4](https://github.com/zuoxingdong/dm2gym/pull/2/files#diff-a2334ef9c72b0a95fe36fdf91f254b60R72), [5](https://github.com/zuoxingdong/dm2gym/pull/2/files#diff-a2334ef9c72b0a95fe36fdf91f254b60R74) etc.

After this, I think we are ready to merge.

**Comment by aaronsnoswell** [comment]
Hi @zuoxingdong :) I believe the code was already [PEP8 compliant](https://www.python.org/dev/peps/pep-0008/#blank-lines), but I removed the extra whitespace to match the existing coding style. Let me know if there is anything else. Thanks!

**Comment by zuoxingdong** [comment]
LGTM, thank you very much @aaronsnoswell for this PR ! Let's merge it now.

**Pull request merged**
